version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/apps
hooks:
  ApplicationStop:
    - location: aws/scripts/application-stop.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: aws/scripts/before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: aws/scripts/after-install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: aws/scripts/application-start.sh
      timeout: 300
      runas: ubuntu