# Generated by Django 5.0.1 on 2024-02-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_following_profile_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='apple_access_token',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='spotify_access_token',
        ),
        migrations.AddField(
            model_name='customuser',
            name='apple_access_token',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='spotify_access_token',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
