# Generated by Django 5.0.3 on 2024-03-27 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
    ]
