# Generated by Django 5.0.3 on 2024-04-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_profile_profile_image'),
        ('user', '0014_profile_profile_image'),
    ]

    operations = [
    ]
