# Generated by Django 5.0.3 on 2024-04-18 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_spotifytoken_access_token_and_more'),
        ('user', '0015_merge_20240416_1056'),
    ]

    operations = [
    ]
