# Generated by Django 5.0.3 on 2024-04-28 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_merge_20240417_1439'),
        ('user', '0016_merge_20240417_2149'),
    ]

    operations = [
    ]
