# Generated by Django 5.0.1 on 2024-02-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_song_song_clip_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist_features',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
