# Generated by Django 5.0.3 on 2024-03-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_playlist_artist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='profile',
        ),
        migrations.AddField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
