# Generated by Django 5.0.1 on 2024-04-16 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_playlist_playlist_thumbnail_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='thumb_nail',
            new_name='album_thumb_nail_location',
        ),
    ]
