# Generated by Django 5.0.1 on 2024-04-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_rename_album_thumb_nail_location_album_album_thumbnail_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ManyToManyField(related_name='albums', to='music.song'),
        ),
    ]
