name: Run Tests

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - dev  # Change this to the branch you want to trigger the workflow on

jobs:
  test:
    runs-on: ubuntu-latest  # You can choose a different operating system if needed

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Change this to your Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Adjust based on your project setup

    - name: Configure Environment Variables
      run: echo "${{ secrets.KEYS_ENV_CONTENTS }}" > keys.env
      
    - name: Run Tests
      run: |
        python -m unittest testing.test_POCsong testing.test_POCspotify # Adjust the test command based on your project setup